# Generated by Django 5.0.4 on 2024-04-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.CharField(blank=True, max_length=150, null=True)),
                ('care', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.IntegerField(blank=True, choices=[(1, 'Amarelo'), (2, 'Azul'), (3, 'Vermelho'), (4, 'Branco'), (5, 'Preto'), (6, 'Rosa'), (7, 'Champagne'), (8, 'Laranja'), (9, 'Colorido'), (10, 'Lilás'), (11, 'Marrom')], null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='floriCultura.category')),
            ],
        ),
    ]
