# Generated by Django 5.0.4 on 2024-05-03 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_avaliado', to='floriCultura.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to='floriCultura.client')),
            ],
        ),
    ]
