# Generated by Django 5.0.4 on 2024-05-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0010_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floriCultura.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floriCultura.client')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='floriCultura.coupon')),
                ('items', models.ManyToManyField(to='floriCultura.orderitem')),
            ],
        ),
    ]
