# Generated by Django 5.0.4 on 2024-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0015_alter_address_city_alter_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
