# Generated by Django 5.0.4 on 2024-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0016_alter_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
