# Generated by Django 5.0.4 on 2024-08-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floriCultura', '0022_remove_state_created_at_remove_state_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
    ]
